/*
  Authors : initappz (Rahul Jograna)
  Website : https://initappz.com/
  App Name : Ultimate Salon Full App Flutter V3
  This App Template Source code is licensed as per the
  terms found in the Website https://initappz.com/license
  Copyright and Good Faith Purchasers © 2024-present initappz.
*/
import "package:get/get.dart";

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Profile": "Profile",
          "Inbox": "Inbox",
          "Opps, Please Login or Register first!": "Opps, Please Login or Register first!",
          "Acount": "Acount",
          "Sign In / Sign Up": "Sign In / Sign Up",
          "Edit Profile": "Edit Profile",
          "Product Order": "Product Order",
          "Your Address": "Your Address",
          "Wallet": "Wallet",
          "Refer & Earn": "Refer & Earn",
          "Change Password": "Change Password",
          "Languages": "Languages",
          "Chats": "Chats",
          "Contact Us": "Contact Us",
          "Frequently Asked Questions": "Frequently Asked Questions",
          "Help": "Help",
          "Privacy Policy": "Privacy Policy",
          "Terms & Conditions": "Terms & Conditions",
          "About us": "About us",
          "About": "About",
          "Logout": "Logout",
          "Add New Card": "Add New Card",
          "Email Address": "Email Address",
          "Card Holder Name": "Card Holder Name",
          "Card Number": "Card Number",
          "CVV": "CVV",
          "MM/YY": "MM/YY",
          "ADD CARD": "ADD CARD",
          "Add Review to": "Add Review to",
          "Please rate the quality of service for the appointment you have got!": "Please rate the quality of service for the appointment you have got!",
          "Your comments and suggesstions help us improve the service quality better!": "Your comments and suggesstions help us improve the service quality better!",
          "Write Notes": "Write Notes",
          "Add Review": "Add Review",
          "Save": "Save",
          "Cancle": "Cancle",
          "Select Address": "Select Address",
          "Add Address": "Add Address",
          "Address": "Address",
          "Add New": "Add New",
          "All Categories": "All Categories",
          "Appointment Detail": "Appointment Detail",
          "Booking Date & Time": "Booking Date & Time",
          "Booking Date": "Booking Date",
          "Booking Time": "Booking Time",
          "Services": "Services",
          "Packages": "Packages",
          "Pricing": "Pricing",
          "Discount": "Discount",
          "Wallet Discount": "Wallet Discount",
          "Distance Cost": "Distance Cost",
          "Service Tax": "Service Tax",
          "Total": "Total",
          "Payment Method": "Payment Method",
          "Total Amount": "Total Amount",
          "Your Appoinments Status": "Your Appoinments Status",
          "Cancel": "Cancel",
          "Appointments History": "Appointments History",
          "New": "New",
          "Old": "Old",
          "Grand Total": "Grand Total",
          "Appointment at": "Appointment at",
          "No New Appointment Found!": "No New Appointment Found!",
          "No Past Appointment Found!": "No Past Appointment Found!",
          "Cart": "Cart",
          "Continue": "Continue",
          "Special Discount": "Special Discount",
          "OFF": "OFF",
          "Total Price": "Total Price",
          "Specialist": "Specialist",
          "Salon": "Salon",
          "and more": "and more",
          "No Data Found Near You!": "No Data Found Near You!",
          "Categories": "Categories",
          "Items": "Items",
          "Payments": "Payments",
          "No Data Found!": "No Data Found!",
          "Message...": "Message...",
          "Checkout": "Checkout",
          "min": "min",
          "Bill Details": "Bill Details",
          "item Total": "item Total",
          "Taxes & Charges": "Taxes & Charges",
          "To Pay": "To Pay",
          "Select Date & Time": "Select Date & Time",
          "Access Your": "Access Your",
          "Location": "Location",
          "USE CURRENT LOCATION": "USE CURRENT LOCATION",
          "CHOOSE LOCATION": "CHOOSE LOCATION",
          "Complaints": "Complaints",
          "Issue With": "Issue With",
          "Freelancer": "Freelancer",
          "Select Freelancer": "Select Freelancer",
          "Select product": "Select product",
          "Select service": "Select service",
          "Select package": "Select package",
          "Select Reason": "Select Reason",
          "Title": "Title",
          "Brief of your issue": "Brief of your issue",
          "Comments": "Comments",
          "Write something on issue": "Write something on issue",
          "Upload Image": "Upload Image",
          "Submit": "Submit",
          "Full Name": "Full Name",
          "Message": "Message",
          "Select Coupon": "Select Coupon",
          "Use coupon code": "Use coupon code",
          "Valid until": "Valid until",
          "Choose From": "Choose From",
          "camera": "camera",
          "Camera": "Camera",
          "gallery": "gallery",
          "Gallery": "Gallery",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Gender": "Gender",
          "Male": "Male",
          "Female": "Female",
          "Email": "Email",
          "Code": "Code",
          "Phone": "Phone",
          "Connection Failed": "Connection Failed",
          "Could not connect to network": "Could not connect to network",
          "Please check and try again": "Please check and try again",
          "retry": "retry",
          "Filters": "Filters",
          "Done": "Done",
          "Hairstyle": "Hairstyle",
          "Mackup": "Mackup",
          "Hair Styling": "Hair Styling",
          "Spa": "Spa",
          "Facial Mackup": "Facial Mackup",
          "Trim & Saving": "Trim & Saving",
          "Rating": "Rating",
          "4.0 Star": "4.0 Star",
          "Other": "Other",
          "Distance": "Distance",
          "Sort by": "Sort by",
          "Most Popular": "Most Popular",
          "Cost Low To High": "Cost Low To High",
          "Cost High To Low": "Cost High To Low",
          "Price": "Price",
          "Find Location": "Find Location",
          "Search location": "Search location",
          "Use My Current Location": "Use My Current Location",
          "Confirm Location": "Confirm Location",
          "Verify your phone number": "Verify your phone number",
          "success_verified": "success_verified",
          "Search salon, spa and barber": "Search salon, spa and barber",
          "Find and book best services": "Find and book best services",
          "Top Categories": "Top Categories",
          "View all": "View all",
          "Top Specialist": "Top Specialist",
          "Top Salon": "Top Salon",
          "Book": "Book",
          "Top Products": "Top Products",
          "ADD": "ADD",
          "Book Services": "Book Services",
          "Packages Details": "Packages Details",
          "Book Now": "Book Now",
          "Remove Package": "Remove Package",
          "Services Included": "Services Included",
          "Packages Name": "Packages Name",
          "Duration": "Duration",
          "Photos": "Photos",
          "Payment": "Payment",
          "Offers & Benefits": "Offers & Benefits",
          "Apply Coupon Code": "Apply Coupon Code",
          "Coupon Applied": "Coupon Applied",
          "Available Balance": "Available Balance",
          "Notes For Service": "Notes For Service",
          "Appoinments notes": "Appoinments notes",
          "item Discount": "item Discount",
          "Distance Charge": "Distance Charge",
          "Please Add Your Address": "Please Add Your Address",
          "Pay": "Pay",
          "Slots": "Slots",
          "Select Date": "Select Date",
          "No Slots Found": "No Slots Found",
          "Select Slots": "Select Slots",
          "Make Payment": "Make Payment",
          "Save Todo and Retrun to List": "Save Todo and Retrun to List",
          "Find Barbarshop Nearby !": "Find Barbarshop Nearby !",
          "Attractive Promotions !": "Attractive Promotions !",
          "Professional Specialist !": "Professional Specialist !",
          "Get Specialist at your door steps !": "Get Specialist at your door steps !",
          "Buy from trusted professional !": "Buy from trusted professional !",
          "Skip": "Skip",
          "Next": "Next",
          "Previous": "Previous",
          "Get Started": "Get Started",
          "English": "English",
          "Hindi": "Hindi",
          "Spanish": "Spanish",
          "Password": "Password",
          "Forgot Password ?": "Forgot Password ?",
          "Log In": "Log In",
          "Don\"t have account ?": "Don\"t have account ?",
          "Sign Up": "Sign Up",
          "Mobile Number": "Mobile Number",
          "Add New Address": "Add New Address",
          "House / Flat No.": "House / Flat No.",
          "Landmark": "Landmark",
          "Pincode": "Pincode",
          "Save Address": "Save Address",
          "Home": "Home",
          "Work": "Work",
          "Update": "Update",
          "Service at": "Service at",
          "At Home": "At Home",
          "At Salon": "At Salon",
          "Order Detail": "Order Detail",
          "Order At": "Order At",
          "Orders": "Orders",
          "X": "X",
          "Your Order Status": "Your Order Status",
          "Order History": "Order History",
          "Order Id": "Order Id",
          "No New Orders Found!": "No New Orders Found!",
          "No Past Orders Found!": "No Past Orders Found!",
          "Add Notes": "Add Notes",
          "Appoinments notes..": "Appoinments notes..",
          "Pay With Stripe": "Pay With Stripe",
          "Expiry": "Expiry",
          "Products Details": "Products Details",
          "Add To Cart": "Add To Cart",
          "Sold By": "Sold By",
          "Categories Info": "Categories Info",
          "Sub Categories Info": "Sub Categories Info",
          "Descriptions": "Descriptions",
          "Special Price": "Special Price",
          "Off": "Off",
          "Only 5 Days Left": "Only 5 Days Left",
          "Disclaimer": "Disclaimer",
          "Related Products": "Related Products",
          "Reviews": "Reviews",
          "Write your review": "Write your review",
          "Leave your experience..": "Leave your experience..",
          "post": "post",
          "Kevin Doyle": "Kevin Doyle",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters":
              "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters",
          "Products": "Products",
          "Sort By": "Sort By",
          "Invite Now": "Invite Now",
          "Create an Account": "Create an Account",
          "Referral Code": "Referral Code",
          "By continuing, you agree to our": "By continuing, you agree to our",
          "Terms of Service": "Terms of Service",
          "You have already account ?": "You have already account ?",
          "Reset Password": "Reset Password",
          "Enter your email address or phone number and we will send a verification code to generate a new password": "Enter your email address or phone number and we will send a verification code to generate a new password",
          "Send OTP": "Send OTP",
          "Generate New Password": "Generate New Password",
          "New Password": "New Password",
          "Confirm Password": "Confirm Password",
          "Update Password": "Update Password",
          "Your Location": "Your Location",
          "Search For Salon, Services.....": "Search For Salon, Services.....",
          "Salons": "Salons",
          "KM": "KM",
          "OPEN": "OPEN",
          "Website": "Website",
          "Call": "Call",
          "Chat": "Chat",
          "Direction": "Direction",
          "Share": "Share",
          "Salon Specialist": "Salon Specialist",
          "Opening Hour": "Opening Hour",
          "Get Direction": "Get Direction",
          "Type": "Type",
          "View": "View",
          "Appointment": "Appointment",
          "Select Specialist": "Select Specialist",
          "Portfolio": "Portfolio",
          "Basic Info": "Basic Info",
          "No Internet Connection": "No Internet Connection",
          "Developed By": "Developed By",
          "NearBy": "NearBy",
          "Shop": "Shop",
          "Appoinment": "Appoinment",
          "Account": "Account",
          "Top Packages & Offers": "Top Packages & Offers",
          "Ms.Jolly Jonthon": "Ms.Jolly Jonthon",
          "Aromatherapy": "Aromatherapy",
          "Fee start from": "Fee start from",
          "All Transactions": "All Transactions",
          "Book an Appointment for Salon, Spa & Barber": "Book an Appointment for Salon, Spa & Barber",
          "Connect with Google": "Connect with Google",
          "Connect with Facebook": "Connect with Facebook",
          "Already have an account?": "Already have an account?",
          "Please wait": "Please wait",
          "All fields are required": "All fields are required",
          "Card Information Saved": "Card Information Saved",
          "Please add comments": "Please add comments",
          "Review Saved": "Review Saved",
          "Others": "Others",
          "item remove successfully": "item remove successfully",
          "NA": "NA",
          "COD": "COD",
          "Stripe": "Stripe",
          "PayPal": "PayPal",
          "Paytm": "Paytm",
          "Razorpay": "Razorpay",
          "Instamojo": "Instamojo",
          "Paystack": "Paystack",
          "Flutterwave": "Flutterwave",
          "Accepted": "Accepted",
          "Rejected by Freelancer": "Rejected by Freelancer",
          "Ongoing": "Ongoing",
          "Completed": "Completed",
          "Cancelled": "Cancelled",
          "Refunded": "Refunded",
          "Delayed": "Delayed",
          "Panding Payment": "Panding Payment",
          "Status Updated": "Status Updated",
          "Rate Your Appointment": "Rate Your Appointment",
          "Owner": "Owner",
          "Could not launch": "Could not launch",
          "Choose": "Choose",
          "Featching Location": "Featching Location",
          "The product arrived too late": "The product arrived too late",
          "The product did not match the description": "The product did not match the description",
          "The purchase was fraudulent": "The purchase was fraudulent",
          "The product was damaged or defective": "The product was damaged or defective",
          "The merchant shipped the wrong item": "The merchant shipped the wrong item",
          "Wrong Item Size or Wrong Product Shipped": "Wrong Item Size or Wrong Product Shipped",
          "Driver arrived too late": "Driver arrived too late",
          "Driver behavior": "Driver behavior",
          "Freelacer behavior": "Freelacer behavior",
          "Issue with Payment Amount": "Issue with Payment Amount",
          "Freelancer was fraudulent": "Freelancer was fraudulent",
          "Related to service": "Related to service",
          "Satisfaction of services": "Satisfaction of services",
          "Choose Issue With": "Choose Issue With",
          "Choose Reason": "Choose Reason",
          "Choose Service": "Choose Service",
          "Choose Package": "Choose Package",
          "Choose Product": "Choose Product",
          "Complaints registered": "Complaints registered",
          "New Mail Request Received": "New Mail Request Received",
          "You have received new mail": "You have received new mail",
          "New Contact Details": "New Contact Details",
          "We have received your request, we will respond on your issue soon": "We have received your request, we will respond on your issue soon",
          "Alert!": "Alert!",
          "Contact Information Sent": "Contact Information Sent",
          "Okay": "Okay",
          "Location services are disabled": "Location services are disabled",
          "Location permissions are permanently denied, we cannot request permissions": "Location permissions are permanently denied, we cannot request permissions",
          "We already have product with other freelancer": "We already have product with other freelancer",
          "We already have service or package with other salon or with freelancer": "We already have service or package with other salon or with freelancer",
          "Sorry we deliver the order near to": "Sorry we deliver the order near to",
          "Appoinments once placed cannot be cancelled and non-refundable": "Appoinments once placed cannot be cancelled and non-refundable",
          "Are you sure": "Are you sure",
          "Thank You!": "Thank You!",
          "For Your Appoinment": "For Your Appoinment",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout":
              "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout",
          "TRACK MY APPOINTMENT": "TRACK MY APPOINTMENT",
          "BACK TO HOME": "BACK TO HOME",
          "Sunday": "Sunday",
          "Monday": "Monday",
          "Tuesday": "Tuesday",
          "Wednesday": "Wednesday",
          "Thursday": "Thursday",
          "Friday": "Friday",
          "Saturday": "Saturday",
          "Please select Slots": "Please select Slots",
          "Email is not valid": "Email is not valid",
          "Access denied": "Access denied",
          "error": "error",
          "Phone Number is required": "Phone Number is required",
          "Something went wrong while signup": "Something went wrong while signup",
          "Something went wrong": "Something went wrong",
          "Verification": "Verification",
          "We have sent verification code on": "We have sent verification code on",
          "Verify": "Verify",
          "Successfully Added": "Successfully Added",
          "Successfully Updated": "Successfully Updated",
          "Please select payment method": "Please select payment method",
          "We have already select product with other freelancer": "We have already select product with other freelancer",
          "Share with buddies": "Share with buddies",
          "Copied to clipboard": "Copied to clipboard",
          "Hey Buddy download": "Hey Buddy download",
          "Your friend": "Your friend",
          "has invited you to": "has invited you to",
          "from app store and use my code": "from app store and use my code",
          "while sign up we both will get": "while sign up we both will get",
          "wallet amount": "wallet amount",
          "Password mismatch": "Password mismatch",
          "No Website Found": "No Website Found",
          "Please checkout this salon": "Please checkout this salon",
          "Share with": "Share with",
          "Please select specialist": "Please select specialist",
          "Yes, Place Order": "Yes, Place Order",
          "Please select card": "Please select card",
          "Creating Order": "Creating Order",
          "TRACK MY ORDERS": "TRACK MY ORDERS",
          "For Your Orders": "For Your Orders",
          "Order notes..": "Order notes.."
        },
        "hi_IN": {
          "Profile": "प्रोफ़ाइल",
          "Inbox": "इनबॉक्स",
          "Opps, Please Login or Register first!": "Opps, कृपया लॉगिन करें या पहले पंजीकरण करें!",
          "Acount": "एक गिनती",
          "Sign In / Sign Up": "प्रवेश या साइन अप",
          "Edit Profile": "प्रोफ़ाइल संपादित करें",
          "Product Order": "उत्पाद आदेश",
          "Your Address": "तुम्हारा पता",
          "Wallet": "बटुआ",
          "Refer & Earn": "देखें और अर्जित करना",
          "Change Password": "पासवर्ड बदलें",
          "Languages": "बोली",
          "Chats": "चैट",
          "Contact Us": "संपर्क करें",
          "Frequently Asked Questions": "अधिकतर पूछे जाने वाले सवाल",
          "Help": "मदद करना",
          "Privacy Policy": "गोपनीयता नीति",
          "Terms & Conditions": "नियम एवं शर्तें",
          "About us": "हमारे बारे में",
          "About": "के बारे में",
          "Logout": "लॉग आउट",
          "Add New Card": "नया कार्ड जोड़ें",
          "Email Address": "ईमेल पता",
          "Card Holder Name": "कार्डधारक का नाम",
          "Card Number": "कार्ड नंबर",
          "CVV": "सीवीवी",
          "MM/YY": "महीना साल",
          "ADD CARD": "कार्ड जोड़ें",
          "Add Review to": "की समीक्षा जोड़ें",
          "Please rate the quality of service for the appointment you have got!": "कृपया आपके द्वारा मिली नियुक्ति के लिए सेवा की गुणवत्ता को दर करें!",
          "Your comments and suggesstions help us improve the service quality better!": "आपकी टिप्पणियां और शर्करा हमें सेवा की गुणवत्ता को बेहतर ढंग से बेहतर बनाने में मदद करते हैं!",
          "Write Notes": "नोट लिख",
          "Add Review": "समीक्षा जोड़ें",
          "Save": "बचाना",
          "Cancle": "चकमा देना",
          "Select Address": "पता चुनें",
          "Add Address": "पता जोड़ें",
          "Address": "पता",
          "Add New": "नया जोड़ो",
          "All Categories": "सब वर्ग",
          "Appointment Detail": "नियुक्ति विवरण",
          "Booking Date & Time": "बुकिंग दिनांक और समय",
          "Booking Date": "बुक करने की तिथि",
          "Booking Time": "बुकिंग समय",
          "Services": "सेवाएं",
          "Packages": "संकुल",
          "Pricing": "मूल्य निर्धारण",
          "Discount": "छूट",
          "Wallet Discount": "बटुआ छूट",
          "Distance Cost": "दूरी लागत",
          "Service Tax": "सेवा कर",
          "Total": "कुल",
          "Payment Method": "भुगतान का तरीका",
          "Total Amount": "कुल राशि",
          "Your Appoinments Status": "आपकी appoinments स्थिति",
          "Cancel": "रद्द करना",
          "Appointments History": "नियुक्ति इतिहास",
          "New": "नया",
          "Old": "पुराना",
          "Grand Total": "कुल योग",
          "Appointment at": "नियुक्ति",
          "No New Appointment Found!": "कोई नई नियुक्ति नहीं मिली!",
          "No Past Appointment Found!": "कोई पिछली नियुक्ति नहीं मिली!",
          "Cart": "कार्ट",
          "Continue": "जारी रखना",
          "Special Discount": "विशेष छूट",
          "OFF": "बंद",
          "Total Price": "कुल कीमत",
          "Specialist": "SPECIALIST",
          "Salon": "सैलून",
          "and more": "और अधिक",
          "No Data Found Near You!": "आपके पास कोई डेटा नहीं मिला!",
          "Categories": "श्रेणियाँ",
          "Items": "सामान",
          "Payments": "भुगतान",
          "No Data Found!": "कोई डेटा नहीं मिला!",
          "Message...": "संदेश...",
          "Checkout": "चेक आउट",
          "min": "मिनट",
          "Bill Details": "बिल विवरण",
          "item Total": "आइटम का कुल",
          "Taxes & Charges": "कर और प्रभार",
          "To Pay": "भुगतान करने के लिए",
          "Select Date & Time": "दिनांक और समय का चयन करें",
          "Access Your": "अपने एक्सेस करें",
          "Location": "स्थान",
          "USE CURRENT LOCATION": "वर्तमान स्थान का उपयोग करें",
          "CHOOSE LOCATION": "स्थान का चयन",
          "Complaints": "शिकायतों",
          "Issue With": "के साथ जारी करना",
          "Freelancer": "फ्रीलांसर",
          "Select Freelancer": "फ्रीलांसर का चयन करें",
          "Select product": "उत्पाद का चयन करें",
          "Select service": "सेवा का चयन करें",
          "Select package": "पैकेज का चयन करें",
          "Select Reason": "कारण का चयन करें",
          "Title": "शीर्षक",
          "Brief of your issue": "अपने मुद्दे का संक्षिप्त",
          "Comments": "टिप्पणियाँ",
          "Write something on issue": "मुद्दे पर कुछ लिखें",
          "Upload Image": "तस्विर अपलोड करना",
          "Submit": "प्रस्तुत करना",
          "Full Name": "पूरा नाम",
          "Message": "संदेश",
          "Select Coupon": "कूपन का चयन करें",
          "Use coupon code": "कूपन कोड का उपयोग करें",
          "Valid until": "तब तक वैध",
          "Choose From": "से चुनें",
          "camera": "कैमरा",
          "Camera": "कैमरा",
          "gallery": "गेलरी",
          "Gallery": "गेलरी",
          "First Name": "पहला नाम",
          "Last Name": "उपनाम",
          "Gender": "लिंग",
          "Male": "पुरुष",
          "Female": "मादा",
          "Email": "ईमेल",
          "Code": "कोड",
          "Phone": "फ़ोन",
          "Connection Failed": "कनेक्शन विफल",
          "Could not connect to network": "नेटवर्क से कनेक्ट नहीं हो सका",
          "Please check and try again": "कृपया जाँच करें और पुनः प्रयास करें",
          "retry": "पुन: प्रयास करें",
          "Filters": "फिल्टर",
          "Done": "पूर्ण",
          "Hairstyle": "बाल शैली",
          "Mackup": "मैकप",
          "Hair Styling": "बाल बनाना",
          "Spa": "स्पा",
          "Facial Mackup": "फेशियल मैकप",
          "Trim & Saving": "ट्रिम और बचत",
          "Rating": "रेटिंग",
          "4.0 Star": "4.0 स्टार",
          "Other": "अन्य",
          "Distance": "दूरी",
          "Sort by": "इसके अनुसार क्रमबद्ध करें",
          "Most Popular": "सबसे लोकप्रिय",
          "Cost Low To High": "उच्च से उच्च लागत",
          "Cost High To Low": "कम से कम लागत",
          "Price": "कीमत",
          "Find Location": "स्थान खोजें",
          "Search location": "खोज स्थान",
          "Use My Current Location": "मेरे वर्तमान स्थान का उपयोग करें",
          "Confirm Location": "स्थान की पुष्टि करें",
          "Verify your phone number": "अपना फोन नम्बर सत्यापित करें",
          "success_verified": "Success_verified",
          "Search salon, spa and barber": "खोज सैलून, स्पा और नाई",
          "Find and book best services": "सर्वश्रेष्ठ सेवाएं खोजें और बुक करें",
          "Top Categories": "शीर्ष श्रेणियां",
          "View all": "सभी देखें",
          "Top Specialist": "शीर्ष विशेषज्ञ",
          "Top Salon": "शीर्ष सैलून",
          "Book": "किताब",
          "Top Products": "शीर्ष उत्पाद",
          "ADD": "जोड़ें",
          "Book Services": "बही सेवाएँ",
          "Packages Details": "पैकेज विवरण",
          "Book Now": "अभी बुक करें",
          "Remove Package": "हटाएं पैकेज",
          "Services Included": "सेवाएं शामिल हैं",
          "Packages Name": "पैकेज का नाम",
          "Duration": "अवधि",
          "Photos": "तस्वीरें",
          "Payment": "भुगतान",
          "Offers & Benefits": "प्रस्ताव और लाभ",
          "Apply Coupon Code": "कूपन कोड लागू करें",
          "Coupon Applied": "कूपन लागू किया हुआ",
          "Available Balance": "उपलब्ध शेष राशि",
          "Notes For Service": "सेवा के लिए नोट्स",
          "Appoinments notes": "नियुक्ति नोट्स",
          "item Discount": "मद की छूट",
          "Distance Charge": "दूरस्थ प्रभार",
          "Please Add Your Address": "कृपया अपना पता जोड़ें",
          "Pay": "भुगतान करना",
          "Slots": "स्लॉट्स",
          "Select Date": "तारीख़ चुनें",
          "No Slots Found": "कोई स्लॉट नहीं मिला",
          "Select Slots": "स्लॉट का चयन करें",
          "Make Payment": "भुगतान करो",
          "Save Todo and Retrun to List": "टोडो और रेट्रन को सूचीबद्ध करने के लिए सहेजें",
          "Find Barbarshop Nearby !": "पास में बर्बरशॉप खोजें!",
          "Attractive Promotions !": "आकर्षक प्रचार!",
          "Professional Specialist !": "पेशेवर विशेषज्ञ!",
          "Get Specialist at your door steps !": "अपने दरवाजे के कदमों पर विशेषज्ञ प्राप्त करें!",
          "Buy from trusted professional !": "विश्वसनीय पेशेवर से खरीदें!",
          "Skip": "छोड़ें",
          "Next": "अगला",
          "Previous": "पिछला",
          "Get Started": "शुरू हो जाओ",
          "English": "अंग्रेज़ी",
          "Hindi": "हिन्दी",
          "Spanish": "स्पैनिश",
          "Password": "पासवर्ड",
          "Forgot Password ?": "पासवर्ड भूल गए ?",
          "Log In": "लॉग इन करें",
          "Don\"t have account ?": "डॉन \"टी का खाता है?",
          "Sign Up": "साइन अप करें",
          "Mobile Number": "मोबाइल नंबर",
          "Add New Address": "नया पता जोड़ें",
          "House / Flat No.": "हाउस / फ्लैट नं।",
          "Landmark": "सीमाचिह्न",
          "Pincode": "पिन कोड",
          "Save Address": "सहेजें पता",
          "Home": "घर",
          "Work": "काम",
          "Update": "अद्यतन",
          "Service at": "सेवा करना",
          "At Home": "घर पर",
          "At Salon": "सैलून में",
          "Order Detail": "ऑर्डर विवरण",
          "Order At": "आदेश देना",
          "Orders": "आदेश",
          "X": "एक्स",
          "Your Order Status": "आपकी ऑर्डर की स्थिति",
          "Order History": "आदेश इतिहास",
          "Order Id": "आदेश ID",
          "No New Orders Found!": "कोई नया आदेश नहीं मिला!",
          "No Past Orders Found!": "कोई अतीत के आदेश नहीं मिले!",
          "Add Notes": "नोट जोड़ें",
          "Appoinments notes..": "Appoinments नोट्स ..",
          "Pay With Stripe": "पट्टी के साथ भुगतान करें",
          "Expiry": "समाप्ति",
          "Products Details": "उत्पाद विवरण",
          "Add To Cart": "कार्ट में जोड़ें",
          "Sold By": "द्वारा बेचा",
          "Categories Info": "श्रेणियां जानकारी",
          "Sub Categories Info": "उप श्रेणियों की जानकारी",
          "Descriptions": "विवरण",
          "Special Price": "विशेष मूल्य",
          "Off": "बंद",
          "Only 5 Days Left": "केवल 5 दिन बचे हैं",
          "Disclaimer": "अस्वीकरण",
          "Related Products": "संबंधित उत्पाद",
          "Reviews": "समीक्षा",
          "Write your review": "अपनी समीक्षा लिखिए",
          "Leave your experience..": "अपना अनुभव छोड़ दो ।।",
          "post": "पद",
          "Kevin Doyle": "केविन डॉयल",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters":
              "यह एक लंबे समय से स्थापित तथ्य है कि एक पाठक अपने लेआउट को देखते समय एक पृष्ठ की पठनीय सामग्री से विचलित हो जाएगा। Lorem ipsum का उपयोग करने की बात यह है कि इसमें अक्षरों का अधिक-या-कम सामान्य वितरण है",
          "Products": "उत्पादों",
          "Sort By": "इसके अनुसार क्रमबद्ध करें",
          "Invite Now": "अब आमंत्रित करें",
          "Create an Account": "खाता बनाएं",
          "Referral Code": "रेफरल कोड",
          "By continuing, you agree to our": "जारी रखने से, आप हमारे लिए सहमत हैं",
          "Terms of Service": "सेवा की शर्तें",
          "You have already account ?": "आप पहले से ही खाते हैं?",
          "Reset Password": "पासवर्ड रीसेट",
          "Enter your email address or phone number and we will send a verification code to generate a new password": "अपना ईमेल पता या फ़ोन नंबर दर्ज करें और हम एक नया पासवर्ड उत्पन्न करने के लिए एक सत्यापन कोड भेजेंगे",
          "Send OTP": "OTP भेजें",
          "Generate New Password": "नया पासवर्ड उत्पन्न करें",
          "New Password": "नया पासवर्ड",
          "Confirm Password": "पासवर्ड की पुष्टि कीजिये",
          "Update Password": "पासवर्ड अपडेट करें",
          "Your Location": "आपका स्थान",
          "Search For Salon, Services.....": "सैलून, सेवाओं के लिए खोज .....",
          "Salons": "सैलून",
          "KM": "किमी",
          "OPEN": "खोलना",
          "Website": "वेबसाइट",
          "Call": "बुलाना",
          "Chat": "बात करना",
          "Direction": "दिशा",
          "Share": "शेयर करना",
          "Salon Specialist": "सैलून विशेषज्ञ",
          "Opening Hour": "खुलने का समय",
          "Get Direction": "दिशा प्राप्त करना",
          "Type": "टाइप",
          "View": "राय",
          "Appointment": "नियुक्ति",
          "Select Specialist": "विशेषज्ञ का चयन करें",
          "Portfolio": "पोर्टफोलियो",
          "Basic Info": "बुनियादी जानकारी",
          "No Internet Connection": "कोई इंटरनेट कनेक्शन नहीं",
          "Developed By": "द्वारा विकसित",
          "NearBy": "आस-पास",
          "Shop": "दुकान",
          "Appoinment": "नियुक्ति",
          "Account": "खाता",
          "Top Packages & Offers": "शीर्ष पैकेज और ऑफ़र",
          "Ms.Jolly Jonthon": "सुश्रीजोली जॉनथन",
          "Aromatherapy": "aromatherapy",
          "Fee start from": "शुल्क शुरू",
          "All Transactions": "सभी लेन - देन",
          "Book an Appointment for Salon, Spa & Barber": "सैलून, स्पा और नाई के लिए एक नियुक्ति बुक करें",
          "Connect with Google": "Google से कनेक्ट करें",
          "Connect with Facebook": "फेसबुक से कनेक्ट करें",
          "Already have an account?": "क्या आपके पास पहले से एक खाता मौजूद है?",
          "Please wait": "कृपया प्रतीक्षा करें",
          "All fields are required": "सभी फ़ील्ड आवश्यक हैं",
          "Card Information Saved": "कार्ड की जानकारी सहेजा",
          "Please add comments": "कृपया टिप्पणियाँ जोड़ें",
          "Review Saved": "समीक्षा सहेजे गए",
          "Others": "अन्य",
          "item remove successfully": "आइटम सफलतापूर्वक निकालें",
          "NA": "ना",
          "COD": "सीओडी",
          "Stripe": "पट्टी",
          "PayPal": "पेपैल",
          "Paytm": "Paytm",
          "Razorpay": "रज़ोरपे",
          "Instamojo": "इंस्टैमोजो",
          "Paystack": "अदायगी",
          "Flutterwave": "फड़फड़ाना",
          "Accepted": "को स्वीकृत",
          "Rejected by Freelancer": "फ्रीलांसर द्वारा अस्वीकृत",
          "Ongoing": "चल रहे",
          "Completed": "पूरा हुआ",
          "Cancelled": "रद्द",
          "Refunded": "वापसी की गई है",
          "Delayed": "देर से",
          "Panding Payment": "अदायगी",
          "Status Updated": "अद्यतन की गई स्थिति",
          "Rate Your Appointment": "अपनी नियुक्ति की दर",
          "Owner": "स्वामी",
          "Could not launch": "लॉन्च नहीं कर सका",
          "Choose": "चुनना",
          "Featching Location": "करतब स्थान",
          "The product arrived too late": "उत्पाद बहुत देर से आ गया",
          "The product did not match the description": "उत्पाद विवरण से मेल नहीं खाता था",
          "The purchase was fraudulent": "खरीद फर्जी थी",
          "The product was damaged or defective": "उत्पाद क्षतिग्रस्त या दोषपूर्ण था",
          "The merchant shipped the wrong item": "व्यापारी ने गलत आइटम भेज दिया",
          "Wrong Item Size or Wrong Product Shipped": "गलत आइटम का आकार या गलत उत्पाद भेज दिया",
          "Driver arrived too late": "ड्राइवर बहुत देर से पहुंचे",
          "Driver behavior": "चालक व्यवहार",
          "Freelacer behavior": "फ़्रीलेसर व्यवहार",
          "Issue with Payment Amount": "भुगतान राशि के साथ जारी करें",
          "Freelancer was fraudulent": "फ्रीलांसर फर्जी था",
          "Related to service": "सेवा से संबंधित",
          "Satisfaction of services": "सेवाओं की संतुष्टि",
          "Choose Issue With": "के साथ समस्या चुनें",
          "Choose Reason": "कारण चुनें",
          "Choose Service": "सेवा चुनें",
          "Choose Package": "पैकेज चुनें",
          "Choose Product": "उत्पाद चुनें",
          "Complaints registered": "पंजीकृत शिकायतें",
          "New Mail Request Received": "नया मेल अनुरोध प्राप्त हुआ",
          "You have received new mail": "आपको नया मेल मिला है",
          "New Contact Details": "नया संपर्क विवरण",
          "We have received your request, we will respond on your issue soon": "हमें आपका अनुरोध मिला है, हम आपके मुद्दे पर जल्द ही जवाब देंगे",
          "Alert!": "चेतावनी!",
          "Contact Information Sent": "संपर्क जानकारी भेजी",
          "Okay": "ठीक",
          "Location services are disabled": "स्थान सेवाएं अक्षम हैं",
          "Location permissions are permanently denied, we cannot request permissions": "स्थान की अनुमति को स्थायी रूप से अस्वीकार कर दिया जाता है, हम अनुमतियों का अनुरोध नहीं कर सकते",
          "We already have product with other freelancer": "हमारे पास पहले से ही अन्य फ्रीलांसर के साथ उत्पाद है",
          "We already have service or package with other salon or with freelancer": "हमारे पास पहले से ही अन्य सैलून के साथ या फ्रीलांसर के साथ सेवा या पैकेज है",
          "Sorry we deliver the order near to": "क्षमा करें, हम ऑर्डर के पास वितरित करते हैं",
          "Appoinments once placed cannot be cancelled and non-refundable": "एक बार रखे गए appoinments को रद्द नहीं किया जा सकता है और गैर-वापसी योग्य नहीं है",
          "Are you sure": "क्या आपको यकीन है",
          "Thank You!": "धन्यवाद!",
          "For Your Appoinment": "आपकी अपील के लिए",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout":
              "यह एक लंबे समय से स्थापित तथ्य है कि एक पाठक अपने लेआउट को देखते समय एक पृष्ठ की पठनीय सामग्री से विचलित हो जाएगा",
          "TRACK MY APPOINTMENT": "मेरी नियुक्ति को ट्रैक करें",
          "BACK TO HOME": "घर वापिस जा रहा हूँ",
          "Sunday": "रविवार",
          "Monday": "सोमवार",
          "Tuesday": "मंगलवार",
          "Wednesday": "बुधवार",
          "Thursday": "गुरुवार",
          "Friday": "शुक्रवार",
          "Saturday": "शनिवार",
          "Please select Slots": "कृपया स्लॉट का चयन करें",
          "Email is not valid": "विद्युतडाक मान्य नहीं है",
          "Access denied": "पहुंच अस्वीकृत",
          "error": "गलती",
          "Phone Number is required": "फोन नंबर की आवश्यकता है",
          "Something went wrong while signup": "साइनअप करते समय कुछ गलत हुआ",
          "Something went wrong": "कुछ गलत हो गया",
          "Verification": "सत्यापन",
          "We have sent verification code on": "हमने सत्यापन कोड भेजा है",
          "Verify": "सत्यापित करना",
          "Successfully Added": "सफलतापूर्वक शामिल",
          "Successfully Updated": "सफलतापूर्वक उत्परिवर्तित",
          "Please select payment method": "कृपया भुगतान विधि का चयन करें",
          "We have already select product with other freelancer": "हम पहले से ही अन्य फ्रीलांसर के साथ उत्पाद का चयन कर चुके हैं",
          "Share with buddies": "मित्रों के साथ साझा करें",
          "Copied to clipboard": "क्लिपबोर्ड पर नकल",
          "Hey Buddy download": "हे दोस्त डाउनलोड",
          "Your friend": "आपके दोस्त",
          "has invited you to": "आपको आमंत्रित किया है",
          "from app store and use my code": "ऐप स्टोर से और मेरे कोड का उपयोग करें",
          "while sign up we both will get": "साइन अप करते समय हम दोनों मिलेंगे",
          "wallet amount": "बटुए की मात्रा",
          "Password mismatch": "पासवर्ड का मेल नहीं हुआ",
          "No Website Found": "कोई वेबसाइट नहीं मिली",
          "Please checkout this salon": "कृपया इस सैलून की जाँच करें",
          "Share with": "के साथ शेयर करें",
          "Please select specialist": "कृपया विशेषज्ञ का चयन करें",
          "Yes, Place Order": "हां, जगह ऑर्डर करें",
          "Please select card": "कृपया कार्ड चुनें",
          "Creating Order": "आदेश बनाना",
          "TRACK MY ORDERS": "मेरे ऑर्डर ट्रैक करें",
          "For Your Orders": "आपके ऑर्डर के लिए",
          "Order notes..": "ऑर्डर नोट.."
        },
        "es_MX": {
          "Profile":"Perfil",
          "Inbox":"Bandeja de entrada",
          "Opps, Please Login or Register first!":"¡Ups, por favor inicia sesión o regístrate primero!",
          "Acount":"Cuenta",
          "Sign In / Sign Up":"Iniciar Sesión / Registrarse",
          "Edit Profile":"Editar Perfil",
          "Product Order":"Pedido de Producto",
          "Your Address":"Tu Dirección",
          "Wallet":"Billetera",
          "Refer & Earn":"Referir y Ganar",
          "Change Password":"Cambiar Contraseña",
          "Languages":"Idiomas",
          "Chats":"Chats",
          "Contact Us":"Contáctanos",
          "Frequently Asked Questions":"Preguntas Frecuentes",
          "Help":"Ayuda",
          "Privacy Policy":"Política de Privacidad",
          "Terms & Conditions":"Términos y Condiciones",
          "About us":"Acerca de Nosotros",
          "About":"Acerca de",
          "Logout":"Cerrar Sesión",
          "Add New Card":"Agregar Nueva Tarjeta",
          "Email Address":"Correo Electrónico",
          "Card Holder Name":"Nombre del Titular de la Tarjeta",
          "Card Number":"Número de Tarjeta",
          "CVV":"CVV",
          "MM/YY":"MM/AA",
          "ADD CARD":"AGREGAR TARJETA",
          "Add Review to":"Agregar Reseña a",
          "Please rate the quality of service for the appointment you have got!":"Por favor califica la calidad del servicio recibido en tu cita.",
          "Your comments and suggesstions help us improve the service quality better!":"Tus comentarios y sugerencias nos ayudan a mejorar la calidad del servicio.",
          "Write Notes":"Escribir Notas",
          "Add Review":"Agregar Reseña",
          "Save":"Guardar",
          "Cancle":"Cancelar",
          "Select Address":"Seleccionar Dirección",
          "Add Address":"Agregar Dirección",
          "Address":"Dirección",
          "Add New":"Agregar Nuevo",
          "All Categories":"Todas las Categorías",
          "Appointment Detail":"Detalle de la Cita",
          "Booking Date & Time":"Fecha y Hora de la Reserva",
          "Booking Date":"Fecha de Reserva",
          "Booking Time":"Hora de Reserva",
          "Services":"Servicios",
          "Packages":"Paquetes",
          "Pricing":"Precios",
          "Discount":"Descuento",
          "Wallet Discount":"Descuento de Billetera",
          "Distance Cost":"Costo por Distancia",
          "Service Tax":"Impuesto de Servicio",
          "Total":"Total",
          "Payment Method":"Método de Pago",
          "Total Amount":"Monto Total",
          "Your Appoinments Status":"Estado de tus Citas",
          "Cancel":"Cancelar",
          "Appointments History":"Historial de Citas",
          "New":"Nuevo",
          "Old":"Antiguo",
          "Grand Total":"Total General",
          "Appointment at":"Cita en",
          "No New Appointment Found!":"No se encontraron citas nuevas.",
          "No Past Appointment Found!":"No se encontraron citas anteriores.",
          "Cart":"Carrito",
          "Continue":"Continuar",
          "Special Discount":"Descuento Especial",
          "OFF":"DESCUENTO",
          "Total Price":"Precio Total",
          "Specialist":"Especialista",
          "Salon":"Salón",
          "and more":"y más",
          "No Data Found Near You!":"No se encontraron datos cerca de ti.",
          "Categories":"Categorías",
          "Items":"Artículos",
          "Payments":"Pagos",
          "No Data Found!":"No se encontraron datos.",
          "Message...":"Mensaje...",
          "Checkout":"Pagar",
          "min":"min",
          "Bill Details":"Detalles de la Factura",
          "item Total":"Total del artículo",
          "Taxes & Charges":"Impuestos y Cargos",
          "To Pay":"A Pagar",
          "Select Date & Time":"Seleccionar Fecha y Hora",
          "Access Your":"Accede a tu",
          "Location":"Ubicación",
          "USE CURRENT LOCATION":"USAR UBICACIÓN ACTUAL",
          "CHOOSE LOCATION":"ELEGIR UBICACIÓN",
          "Complaints":"Quejas",
          "Issue With":"Problema Con",
          "Freelancer":"Freelancer",
          "Select Freelancer":"Seleccionar Freelancer",
          "Select product":"Seleccionar producto",
          "Select service":"Seleccionar servicio",
          "Select package":"Seleccionar paquete",
          "Select Reason":"Seleccionar Motivo",
          "Title":"Título",
          "Brief of your issue":"Resumen de tu problema",
          "Comments":"Comentarios",
          "Write something on issue":"Escribe algo sobre el problema",
          "Upload Image":"Subir Imagen",
          "Submit":"Enviar",
          "Full Name":"Nombre Completo",
          "Message":"Mensaje",
          "Select Coupon":"Seleccionar Cupón",
          "Use coupon code":"Usar código de cupón",
          "Valid until":"Válido hasta",
          "Choose From":"Elegir De",
          "camera":"cámara",
          "Camera":"Cámara",
          "gallery":"galería",
          "Gallery":"Galería",
          "First Name":"Nombre",
          "Last Name":"Apellido",
          "Gender":"Género",
          "Male":"Hombre",
          "Female":"Mujer",
          "Email":"Correo Electrónico",
          "Code":"Código",
          "Phone":"Teléfono",
          "Connection Failed":"Conexión Fallida",
          "Could not connect to network":"No se pudo conectar a la red",
          "Please check and try again":"Por favor revisa e inténtalo de nuevo",
          "retry":"reintentar",
          "Filters":"Filtros",
          "Done":"Hecho",
          "Hairstyle":"Peinado",
          "Mackup":"Maquillaje",
          "Hair Styling":"Estilismo de Cabello",
          "Spa":"Spa",
          "Facial Mackup":"Maquillaje Facial",
          "Trim & Saving":"Recorte y Afeitado",
          "Rating":"Calificación",
          "4.0 Star":"4.0 Estrellas",
          "Other":"Otro",
          "Distance":"Distancia",
          "Sort by":"Ordenar por",
          "Most Popular":"Más Popular",
          "Cost Low To High":"Costo de Menor a Mayor",
          "Cost High To Low":"Costo de Mayor a Menor",
          "Price":"Precio",
          "Find Location":"Encontrar Ubicación",
          "Search location":"Buscar ubicación",
          "Use My Current Location":"Usar mi Ubicación Actual",
          "Confirm Location":"Confirmar Ubicación",
          "Verify your phone number":"Verifica tu número de teléfono",
          "success_verified":"éxito_verificado",
          "Search salon, spa and barber":"Buscar salón, spa y barbería",
          "Find and book best services":"Encuentra y reserva los mejores servicios",
          "Top Categories":"Categorías Principales",
          "View all":"Ver todo",
          "Top Specialist":"Especialista Principal",
          "Top Salon":"Salón Principal",
          "Book":"Reservar",
          "Top Products":"Productos Principales",
          "ADD":"AGREGAR",
          "Book Services":"Reservar Servicios",
          "Packages Details":"Detalles de Paquetes",
          "Book Now":"Reservar Ahora",
          "Remove Package":"Eliminar Paquete",
          "Services Included":"Servicios Incluidos",
          "Packages Name":"Nombre del Paquete",
          "Duration":"Duración",
          "Photos":"Fotos",
          "Payment":"Pago",
          "Offers & Benefits":"Ofertas y Beneficios",
          "Apply Coupon Code":"Aplicar Código de Cupón",
          "Coupon Applied":"Cupón Aplicado",
          "Available Balance":"Saldo Disponible",
          "Notes For Service":"Notas para el Servicio",
          "Appoinments notes":"Notas de Citas",
          "item Discount":"Descuento del artículo",
          "Distance Charge":"Cargo por Distancia",
          "Please Add Your Address":"Por favor, agrega tu dirección",
          "Pay":"Pagar",
          "Slots":"Horarios",
          "Select Date":"Seleccionar Fecha",
          "No Slots Found":"No se encontraron horarios",
          "Select Slots":"Seleccionar Horarios",
          "Make Payment":"Realizar Pago",
          "Save Todo and Retrun to List":"Guardar Tarea y Volver a la Lista",
          "Find Barbarshop Nearby !":"¡Encuentra Barbería Cerca!",
          "Attractive Promotions !":"¡Promociones Atractivas!",
          "Professional Specialist !":"¡Especialista Profesional!",
          "Get Specialist at your door steps !":"Recibe al Especial",
          "Buy from trusted professional !":"Compra de profesionales confiables!",
          "Skip":"Omitir",
          "Next":"Siguiente",
          "Previous":"Anterior",
          "Get Started":"Comenzar",
          "English":"Inglés",
          "Hindi":"Hindi",
          "Spanish":"Español",
          "Password":"Contraseña",
          "Forgot Password ?":"¿Olvidaste tu contraseña?",
          "Log In":"Iniciar Sesión",
          "Don\"t have account ?":"¿No tienes cuenta?",
          "Sign Up":"Regístrate",
          "Mobile Number":"Número de Móvil",
          "Add New Address":"Agregar Nueva Dirección",
          "House / Flat No.":"Casa / Departamento No.",
          "Landmark":"Punto de referencia",
          "Pincode":"Código Postal",
          "Save Address":"Guardar Dirección",
          "Home":"Casa",
          "Work":"Trabajo",
          "Update":"Actualizar",
          "Service at":"Servicio en",
          "At Home":"En Casa",
          "At Salon":"En el Salón",
          "Order Detail":"Detalle del Pedido",
          "Order At":"Ordenar en",
          "Orders":"Pedidos",
          "X":"X",
          "Your Order Status":"Estado de tu Pedido",
          "Order History":"Historial de Pedidos",
          "Order Id":"ID de Pedido",
          "No New Orders Found!":"¡No se encontraron pedidos nuevos!",
          "No Past Orders Found!":"¡No se encontraron pedidos anteriores!",
          "Add Notes":"Agregar Notas",
          "Appoinments notes..":"Notas de Citas...",
          "Pay With Stripe":"Pagar con Stripe",
          "Expiry":"Expiración",
          "Products Details":"Detalles del Producto",
          "Add To Cart":"Agregar al Carrito",
          "Sold By":"Vendido Por",
          "Categories Info":"Información de Categorías",
          "Sub Categories Info":"Información de Subcategorías",
          "Descriptions":"Descripciones",
          "Special Price":"Precio Especial",
          "Off":"Descuento",
          "Only 5 Days Left":"Solo quedan 5 días",
          "Disclaimer":"Descargo de Responsabilidad",
          "Related Products":"Productos Relacionados",
          "Reviews":"Reseñas",
          "Write your review":"Escribe tu reseña",
          "Leave your experience..":"Deja tu experiencia...",
          "post":"publicar",
          "Kevin Doyle":"Kevin Doyle",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters":"Es un hecho bien establecido que un lector se distraerá con el contenido legible de una página cuando mira su diseño. El punto de usar Lorem Ipsum es que tiene una distribución de letras más o menos normal",
          "Products":"Productos",
          "Sort By":"Ordenar Por",
          "Invite Now":"Invitar Ahora",
          "Create an Account":"Crear una Cuenta",
          "Referral Code":"Código de Referencia",
          "By continuing, you agree to our":"Al continuar, aceptas nuestros",
          "Terms of Service":"Términos de Servicio",
          "You have already account ?":"¿Ya tienes una cuenta?",
          "Reset Password":"Restablecer Contraseña",
          "Enter your email address or phone number and we will send a verification code to generate a new password":"Ingresa tu dirección de correo electrónico o número de teléfono y te enviaremos un código de verificación para generar una nueva contraseña",
          "Send OTP":"Enviar OTP",
          "Generate New Password":"Generar Nueva Contraseña",
          "New Password":"Nueva Contraseña",
          "Confirm Password":"Confirmar Contraseña",
          "Update Password":"Actualizar Contraseña",
          "Your Location":"Tu Ubicación",
          "Search For Salon, Services.....":"Buscar Salón, Servicios...",
          "Salons":"Salones",
          "KM":"KM",
          "OPEN":"ABIERTO",
          "Website":"Sitio Web",
          "Call":"Llamar",
          "Chat":"Chat",
          "Direction":"Dirección",
          "Share":"Compartir",
          "Salon Specialist":"Especialista en Salones",
          "Opening Hour":"Hora de Apertura",
          "Get Direction":"Obtener Dirección",
          "Type":"Tipo",
          "View":"Ver",
          "Appointment":"Cita",
          "Select Specialist":"Seleccionar Especialista",
          "Portfolio":"Portafolio",
          "Basic Info":"Información Básica",
          "No Internet Connection":"Sin Conexión a Internet",
          "Developed By":"Desarrollado Por",
          "NearBy":"Cerca",
          "Shop":"Tienda",
          "Appoinment":"Cita",
          "Account":"Cuenta",
          "Top Packages & Offers":"Mejores Paquetes y Ofertas",
          "Ms.Jolly Jonthon":"Sra. Jolly Jonthon",
          "Aromatherapy":"Aromaterapia",
          "Fee start from":"Tarifa desde",
          "All Transactions":"Todas las Transacciones",
          "Book an Appointment for Salon, Spa & Barber":"Reserva una Cita para Salón, Spa y Barbería",
          "Connect with Google":"Conectar con Google",
          "Connect with Facebook":"Conectar con Facebook",
          "Already have an account?":"¿Ya tienes una cuenta?",
          "Please wait":"Por favor espera",
          "All fields are required":"Todos los campos son obligatorios",
          "Card Information Saved":"Información de la Tarjeta Guardada",
          "Please add comments":"Por favor agrega comentarios",
          "Review Saved":"Reseña Guardada",
          "Others":"Otros",
          "item remove successfully":"artículo eliminado con éxito",
          "NA":"N/A",
          "COD":"Contra Reembolso",
          "Stripe":"Stripe",
          "PayPal":"PayPal",
          "Paytm":"Paytm",
          "Razorpay":"Razorpay",
          "Instamojo":"Instamojo",
          "Paystack":"Paystack",
          "Flutterwave":"Flutterwave",
          "Accepted":"Aceptado",
          "Rejected by Freelancer":"Rechazado por Freelancer",
          "Ongoing":"En Proceso",
          "Completed":"Completado",
          "Cancelled":"Cancelado",
          "Refunded":"Reembolsado",
          "Delayed":"Retrasado",
          "Panding Payment":"Pago Pendiente",
          "Status Updated":"Estado Actualizado",
          "Rate Your Appointment":"Califica tu Cita",
          "Owner":"Propietario",
          "Could not launch":"No se pudo iniciar",
          "Choose":"Elegir",
          "Featching Location":"Obteniendo Ubicación",
          "The product arrived too late":"El producto llegó demasiado tarde",
          "The product did not match the description":"El producto no coincidía con la descripción",
          "The purchase was fraudulent":"La compra fue fraudulenta",
          "The product was damaged or defective":"El producto estaba dañado o defectuoso",
          "The merchant shipped the wrong item":"El comerciante envió el artículo incorrecto",
          "Wrong Item Size or Wrong Product Shipped":"Tamaño de artículo incorrecto o producto enviado incorrecto",
          "Driver arrived too late":"El conductor llegó demasiado tarde",
          "Driver behavior":"Comportamiento del conductor",
          "Freelacer behavior":"Comportamiento del freelancer",
          "Issue with Payment Amount":"Problema con el Monto del Pago",
          "Freelancer was fraudulent":"El freelancer fue fraudulento",
          "Related to service":"Relacionado con el servicio",
          "Satisfaction of services":"Satisfacción con los servicios",
          "Choose Issue With":"Elegir Problema Con",
          "Choose Reason":"Elegir Motivo",
          "Choose Service":"Elegir Servicio",
          "Choose Package":"Elegir Paquete",
          "Choose Product":"Elegir Producto",
          "Complaints registered":"Quejas registradas",
          "New Mail Request Received":"Nueva Solicitud de Correo Recibida",
          "You have received new mail":"Has recibido un nuevo correo",
          "New Contact Details":"Nuevos Detalles de Contacto",
          "We have received your request, we will respond on your issue soon":"Hemos recibido tu solicitud, responderemos a tu problema pronto",
          "Alert!":"¡Alerta!",
          "Contact Information Sent":"Información de Contacto Enviada",
          "Okay":"De acuerdo",
          "Location services are disabled":"Los servicios de ubicación están deshabilitados",
          "Location permissions are permanently denied, we cannot request permissions":"Los permisos de ubicación están permanentemente denegados, no podemos solicitar permisos",
          "We already have product with other freelancer":"Ya tenemos producto con otro freelancer",
          "We already have service or package with other salon or with freelancer":"Ya tenemos servicio o paquete con otro salón o con freelancer",
          "Sorry we deliver the order near to":"Lo sentimos, entregamos el pedido cerca de",
          "Appoinments once placed cannot be cancelled and non-refundable":"Las citas, una vez realizadas, no pueden cancelarse y no son reembolsables",
          "Are you sure":"¿Estás seguro?",
          "Thank You!":"¡Gracias!",
          "For Your Appoinment":"Por tu cita",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout":"Es un hecho bien establecido que un lector se distraerá con el contenido legible de una página al mirar su diseño",
          "TRACK MY APPOINTMENT":"SEGUIMIENTO DE MI CITA",
          "BACK TO HOME":"VOLVER A INICIO",
          "Sunday":"Domingo",
          "Monday":"Lunes",
          "Tuesday":"Martes",
          "Wednesday":"Miércoles",
          "Thursday":"Jueves",
          "Friday":"Viernes",
          "Saturday":"Sábado",
          "Please select Slots":"Por favor selecciona horarios",
          "Email is not valid":"El correo electrónico no es válido",
          "Access denied":"Acceso denegado",
          "error":"error",
          "Phone Number is required":"Se requiere número de teléfono",
          "Something went wrong while signup":"Algo salió mal durante el registro",
          "Something went wrong":"Algo salió mal",
          "Verification":"Verificación",
          "We have sent verification code on":"Hemos enviado un código de verificación a",
          "Verify":"Verificar",
          "Successfully Added":"Agregado con éxito",
          "Successfully Updated":"Actualizado con éxito",
          "Please select payment method":"Por favor selecciona el método de pago",
          "We have already select product with other freelancer":"Ya hemos seleccionado producto con otro freelancer",
          "Share with buddies":"Compartir con amigos",
          "Copied to clipboard":"Copiado al portapapeles",
          "Hey Buddy download":"Hey amigo, descarga",
          "Your friend":"Tu amigo",
          "has invited you to":"te ha invitado a",
          "from app store and use my code":"desde la tienda de aplicaciones y usa mi código",
          "while sign up we both will get":"al registrarnos ambos obtendremos",
          "wallet amount":"monto de la billetera",
          "Password mismatch":"Las contraseñas no coinciden",
          "No Website Found":"No se encontró el sitio web",
          "Please checkout this salon":"Por favor revisa este salón",
          "Share with":"Compartir con",
          "Please select specialist":"Por favor selecciona especialista",
          "Yes, Place Order":"Sí, realizar pedido",
          "Please select card":"Por favor selecciona tarjeta",
          "Creating Order":"Creando Pedido",
          "TRACK MY ORDERS":"SEGUIMIENTO DE MIS PEDIDOS",
          "For Your Orders":"Por tus pedidos",
          "Order notes..":"Notas del pedido.."
        },
        "ar_AE": {
          "Profile": "الملف الشخصي",
          "Inbox": "صندوق الوارد",
          "Opps, Please Login or Register first!": "OPPS ، يرجى تسجيل الدخول أو التسجيل أولا!",
          "Acount": "تدفق",
          "Sign In / Sign Up": "تسجيل الدخول / التسجيل",
          "Edit Profile": "تعديل الملف الشخصي",
          "Product Order": "طلبيه",
          "Your Address": "عنوانك",
          "Wallet": "محفظة",
          "Refer & Earn": "الرجوع والكسب",
          "Change Password": "غير كلمة السر",
          "Languages": "اللغات",
          "Chats": "الدردشات",
          "Contact Us": "اتصل بنا",
          "Frequently Asked Questions": "أسئلة مكررة",
          "Help": "مساعدة",
          "Privacy Policy": "سياسة الخصوصية",
          "Terms & Conditions": "البنود و الظروف",
          "About us": "معلومات عنا",
          "About": "حول",
          "Logout": "تسجيل خروج",
          "Add New Card": "أضف بطاقة جديدة",
          "Email Address": "عنوان البريد الالكترونى",
          "Card Holder Name": "إسم صاحب البطاقة",
          "Card Number": "رقم البطاقة",
          "CVV": "CVV",
          "MM/YY": "مم/يي",
          "ADD CARD": "إضافة بطاقة",
          "Add Review to": "أضف مراجعة إلى",
          "Please rate the quality of service for the appointment you have got!": "يرجى تقييم جودة الخدمة لهذا الموعد الذي حصلت عليه!",
          "Your comments and suggesstions help us improve the service quality better!": "تساعدنا تعليقاتك واقتراحاتك على تحسين جودة الخدمة بشكل أفضل!",
          "Write Notes": "اكتب الملاحظات",
          "Add Review": "إضافة مراجعة",
          "Save": "يحفظ",
          "Cancle": "Cancle",
          "Select Address": "حدد العنوان",
          "Add Address": "اضف عنوان",
          "Address": "تبوك",
          "Add New": "اضف جديد",
          "All Categories": "جميع الفئات",
          "Appointment Detail": "تفاصيل الموعد",
          "Booking Date & Time": "تاريخ الحجز والوقت",
          "Booking Date": "تاريخ الحجز",
          "Booking Time": "وقت الحجز",
          "Services": "خدمات",
          "Packages": "حزم",
          "Pricing": "التسعير",
          "Discount": "تخفيض",
          "Wallet Discount": "خصم محفظة",
          "Distance Cost": "تكلفة المسافة",
          "Service Tax": "ضريبة الخدمة",
          "Total": "المجموع",
          "Payment Method": "طريقة الدفع او السداد",
          "Total Amount": "المبلغ الإجمالي",
          "Your Appoinments Status": "حالة appoinments الخاصة بك",
          "Cancel": "يلغي",
          "Appointments History": "تاريخ المواعيد",
          "New": "جديد",
          "Old": "قديم",
          "Grand Total": "المبلغ الإجمالي",
          "Appointment at": "موعد في",
          "No New Appointment Found!": "لم يتم العثور على موعد جديد!",
          "No Past Appointment Found!": "لم يتم العثور على موعد سابق!",
          "Cart": "عربة التسوق",
          "Continue": "يكمل",
          "Special Discount": "خصم خاص",
          "OFF": "إيقاف",
          "Total Price": "السعر الكلي",
          "Specialist": "متخصص",
          "Salon": "صالون",
          "and more": "و اكثر",
          "No Data Found Near You!": "لم يتم العثور على بيانات بالقرب منك!",
          "Categories": "فئات",
          "Items": "العناصر",
          "Payments": "المدفوعات",
          "No Data Found!": "لاتوجد بيانات!",
          "Message...": "رسالة...",
          "Checkout": "الدفع",
          "min": "دقيقة",
          "Bill Details": "تفاصيل فاتورة",
          "item Total": "مجموع الاشياء",
          "Taxes & Charges": "الضرائب والرسوم",
          "To Pay": "لدفع",
          "Select Date & Time": "حدد التاريخ والوقت",
          "Access Your": "الوصول إلى الخاص بك",
          "Location": "موقع",
          "USE CURRENT LOCATION": "استخدام الموقع الحالي",
          "CHOOSE LOCATION": "اختيار موقع",
          "Complaints": "شكاوي",
          "Issue With": "القضية مع",
          "Freelancer": "مستقل",
          "Select Freelancer": "حدد Freelancer",
          "Select product": "حدد المنتج",
          "Select service": "حدد الخدمة",
          "Select package": "حدد الحزمة",
          "Select Reason": "حدد السبب",
          "Title": "عنوان",
          "Brief of your issue": "موجز من مشكلتك",
          "Comments": "تعليقات",
          "Write something on issue": "اكتب شيئًا في القضية",
          "Upload Image": "تحميل الصور",
          "Submit": "يُقدِّم",
          "Full Name": "الاسم الكامل",
          "Message": "رسالة",
          "Select Coupon": "حدد القسيمة",
          "Use coupon code": "استخدم رمز القسيمة",
          "Valid until": "صالح حتى",
          "Choose From": "اختر من",
          "camera": "كاميرا",
          "Camera": "آلة تصوير",
          "gallery": "صالة عرض",
          "Gallery": "صالة عرض",
          "First Name": "الاسم الاول",
          "Last Name": "الكنية",
          "Gender": "جنس",
          "Male": "ذكر",
          "Female": "أنثى",
          "Email": "البريد الإلكتروني",
          "Code": "شفرة",
          "Phone": "هاتف",
          "Connection Failed": "فشل الاتصال",
          "Could not connect to network": "لا يمكن الاتصال بالشبكة",
          "Please check and try again": "يرجى مراجعة وحاول مرة أخرى",
          "retry": "إعادة المحاولة",
          "Filters": "المرشحات",
          "Done": "فعله",
          "Hairstyle": "تسريحه شعر",
          "Mackup": "ماك يصل",
          "Hair Styling": "تسريحة شعر",
          "Spa": "منتجع صحي",
          "Facial Mackup": "الوجه mackup",
          "Trim & Saving": "تقليم وتوفير",
          "Rating": "تقييم",
          "4.0 Star": "4.0 نجمة",
          "Other": "آخر",
          "Distance": "مسافه: بعد",
          "Sort by": "صنف حسب",
          "Most Popular": "الأكثر شعبية",
          "Cost Low To High": "تكلفة منخفضة إلى عالية",
          "Cost High To Low": "تكلفة عالية إلى منخفضة",
          "Price": "سعر",
          "Find Location": "ابحث عن الموقع",
          "Search location": "موقع البحث",
          "Use My Current Location": "استخدم موقعي الحالي",
          "Confirm Location": "تأكيد الموقع",
          "Verify your phone number": "اكد على رقم هاتفك او جوالك",
          "success_verified": "Success_Verified",
          "Search salon, spa and barber": "ابحث صالون وسبا وحلاقة",
          "Find and book best services": "ابحث عن أفضل الخدمات وحجزها",
          "Top Categories": "الفئات العليا",
          "View all": "عرض الكل",
          "Top Specialist": "كبار المتخصصين",
          "Top Salon": "أعلى صالون",
          "Book": "الكتاب",
          "Top Products": "أفضل المنتجات",
          "ADD": "يضيف",
          "Book Services": "خدمات الكتاب",
          "Packages Details": "تفاصيل الحزم",
          "Book Now": "احجز الآن",
          "Remove Package": "إزالة الحزمة",
          "Services Included": "شملت الخدمات",
          "Packages Name": "اسم الحزم",
          "Duration": "مدة",
          "Photos": "الصور",
          "Payment": "دفع",
          "Offers & Benefits": "العروض والفوائد",
          "Apply Coupon Code": "تطبيق رمز القسيمة",
          "Coupon Applied": "كوبون تطبيق",
          "Available Balance": "الرصيد المتوفر",
          "Notes For Service": "ملاحظات للخدمة",
          "Appoinments notes": "ملاحظات appoinments",
          "item Discount": "خصم البند",
          "Distance Charge": "شحنة المسافة",
          "Please Add Your Address": "الرجاء إضافة عنوانك",
          "Pay": "يدفع",
          "Slots": "فتحات",
          "Select Date": "حدد تاريخ",
          "No Slots Found": "لم يتم العثور على فتحات",
          "Select Slots": "حدد فتحات",
          "Make Payment": "قم بالدفع",
          "Save Todo and Retrun to List": "حفظ TODO واسترج",
          "Find Barbarshop Nearby !": "ابحث عن Barbarshop في مكان قريب!",
          "Attractive Promotions !": "عروض ترويجية جذابة!",
          "Professional Specialist !": "أخصائي محترف!",
          "Get Specialist at your door steps !": "احصل على متخصص في خطوات الباب!",
          "Buy from trusted professional !": "شراء من المهنية الموثوقة!",
          "Skip": "يتخطى",
          "Next": "التالي",
          "Previous": "سابق",
          "Get Started": "البدء",
          "English": "إنجليزي",
          "Hindi": "الهندية",
          "Spanish": "الأسبانية",
          "Password": "كلمة المرور",
          "Forgot Password ?": "هل نسيت كلمة السر ؟",
          "Log In": "تسجيل الدخول",
          "Don\"t have account ?": "هل لديك حساب؟",
          "Sign Up": "اشتراك",
          "Mobile Number": "رقم الهاتف المحمول",
          "Add New Address": "أضف عنوانًا جديدًا",
          "House / Flat No.": "منزل / شقة رقم",
          "Landmark": "معلم معروف",
          "Pincode": "pincode",
          "Save Address": "حفظ العنوان",
          "Home": "مسكن",
          "Work": "عمل",
          "Update": "تحديث",
          "Service at": "الخدمة في",
          "At Home": "فى المنزل",
          "At Salon": "في صالون",
          "Order Detail": "تفاصيل الطلب",
          "Order At": "أمر في",
          "Orders": "الطلب #٪ s",
          "X": "x",
          "Your Order Status": "حالة طلبك",
          "Order History": "تاريخ الطلب",
          "Order Id": "رقم التعريف الخاص بالطلب",
          "No New Orders Found!": "لم يتم العثور على أوامر جديدة!",
          "No Past Orders Found!": "لم يتم العثور على أوامر سابقة!",
          "Add Notes": "أضف ملاحظات",
          "Appoinments notes..": "ملاحظات appoinments ..",
          "Pay With Stripe": "دفع مع شريط",
          "Expiry": "انقضاء",
          "Products Details": "تفاصيل المنتجات",
          "Add To Cart": "أضف إلى السلة",
          "Sold By": "تم بيعها من قبل",
          "Categories Info": "معلومات الفئات",
          "Sub Categories Info": "معلومات الفئات الفرعية",
          "Descriptions": "الأوصاف",
          "Special Price": "سعر خاص",
          "Off": "عن",
          "Only 5 Days Left": "بقي 5 أيام فقط",
          "Disclaimer": "تنصل",
          "Related Products": "منتجات ذات صله",
          "Reviews": "المراجعات",
          "Write your review": "اكتب مراجعتك",
          "Leave your experience..": "اترك تجربتك ..",
          "post": "بريد",
          "Kevin Doyle": "كيفن دويل",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters":
              "إنها حقيقة راسخة أن القارئ سوف يصرف انتباهه عن طريق المحتوى القابل للقراءة للصفحة عند النظر إلى تخطيطه. الهدف من استخدام lorem ipsum هو أنه يحتوي على توزيع طبيعي أكثر أو أقل من الحروف",
          "Products": "منتجات",
          "Sort By": "صنف حسب",
          "Invite Now": "دعوة الآن",
          "Create an Account": "انشئ حساب",
          "Referral Code": "كود الإحالة",
          "By continuing, you agree to our": "من خلال الاستمرار ، أنت توافق على",
          "Terms of Service": "شروط الخدمة",
          "You have already account ?": "لديك حساب بالفعل؟",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Enter your email address or phone number and we will send a verification code to generate a new password": "أدخل عنوان بريدك الإلكتروني أو رقم هاتفك وسنرسل رمز التحقق لإنشاء كلمة مرور جديدة",
          "Send OTP": "إرسال OTP",
          "Generate New Password": "إنشاء كلمة مرور جديدة",
          "New Password": "كلمة السر الجديدة",
          "Confirm Password": "تأكيد كلمة المرور",
          "Update Password": "تطوير كلمة السر",
          "Your Location": "موقعك",
          "Search For Salon, Services.....": "ابحث عن الصالون والخدمات .....",
          "Salons": "صالونات",
          "KM": "كم",
          "OPEN": "افتح",
          "Website": "موقع الكتروني",
          "Call": "مكالمة",
          "Chat": "دردشة",
          "Direction": "اتجاه",
          "Share": "يشارك",
          "Salon Specialist": "أخصائي الصالون",
          "Opening Hour": "ساعة الافتتاح",
          "Get Direction": "احصل على اتجاه",
          "Type": "يكتب",
          "View": "رأي",
          "Appointment": "ميعاد",
          "Select Specialist": "حدد متخصص",
          "Portfolio": "مَلَفّ",
          "Basic Info": "معلومات أساسية",
          "No Internet Connection": "لا يوجد اتصال إنترنت",
          "Developed By": "طورت بواسطة",
          "NearBy": "مجاور",
          "Shop": "محل",
          "Appoinment": "ميعاد",
          "Account": "الحساب",
          "Top Packages & Offers": "أعلى الحزم والعروض",
          "Ms.Jolly Jonthon": "السيدة جولي جونثون",
          "Aromatherapy": "العلاج العطري",
          "Fee start from": "تبدأ الرسوم من",
          "All Transactions": "كل الحركات المالية",
          "Book an Appointment for Salon, Spa & Barber": "حجز موعد للصالون والسبا والحلاق",
          "Connect with Google": "تواصل مع Google",
          "Connect with Facebook": "تواصل مع الفيسبوك",
          "Already have an account?": "هل لديك حساب؟",
          "Please wait": "أرجو الإنتظار",
          "All fields are required": "جميع الحقول مطلوبة",
          "Card Information Saved": "تم حفظ معلومات البطاقة",
          "Please add comments": "الرجاء إضافة تعليقات",
          "Review Saved": "مراجعة حفظ",
          "Others": "آحرون",
          "item remove successfully": "العنصر إزالة بنجاح",
          "NA": "نا",
          "COD": "سمك القد",
          "Stripe": "شريط",
          "PayPal": "PayPal",
          "Paytm": "paytm",
          "Razorpay": "رازورباي",
          "Instamojo": "Instamojo",
          "Paystack": "PayStack",
          "Flutterwave": "Flutterwave",
          "Accepted": "وافقت",
          "Rejected by Freelancer": "رفضه المستقل",
          "Ongoing": "جاري التنفيذ",
          "Completed": "مكتمل",
          "Cancelled": "ألغيت",
          "Refunded": "استرداد",
          "Delayed": "تأخير",
          "Panding Payment": "دفع الدفعة",
          "Status Updated": "تم تحديث الحالة",
          "Rate Your Appointment": "قيم موعدك",
          "Owner": "صاحب",
          "Could not launch": "لا يمكن إطلاق",
          "Choose": "يختار",
          "Featching Location": "موقع رائع",
          "The product arrived too late": "وصل المنتج بعد فوات الأوان",
          "The product did not match the description": "المنتج لا يتطابق مع الوصف",
          "The purchase was fraudulent": "كان عملية الشراء احتيالية",
          "The product was damaged or defective": "كان المنتج تضررًا أو معيبًا",
          "The merchant shipped the wrong item": "قام التاجر بشحن العنصر الخاطئ",
          "Wrong Item Size or Wrong Product Shipped": "حجم عنصر خاطئ أو منتج خاطئ",
          "Driver arrived too late": "وصل السائق بعد فوات الأوان",
          "Driver behavior": "سلوك السائق",
          "Freelacer behavior": "سلوك Freelacer",
          "Issue with Payment Amount": "مشكلة مع مبلغ الدفع",
          "Freelancer was fraudulent": "كان مستقل احتيالي",
          "Related to service": "تتعلق بالخدمة",
          "Satisfaction of services": "رضا الخدمات",
          "Choose Issue With": "اختر مشكلة مع",
          "Choose Reason": "اختر السبب",
          "Choose Service": "اختر الخدمة",
          "Choose Package": "اختر الحزمة",
          "Choose Product": "اختر المنتج",
          "Complaints registered": "الشكاوى المسجلة",
          "New Mail Request Received": "تم استلام طلب البريد الجديد",
          "You have received new mail": "لقد تلقيت بريدًا جديدًا",
          "New Contact Details": "تفاصيل الاتصال الجديدة",
          "We have received your request, we will respond on your issue soon": "لقد تلقينا طلبك ، وسوف نرد على مشكلتك قريبًا",
          "Alert!": "انذار!",
          "Contact Information Sent": "معلومات الاتصال المرسلة",
          "Okay": "تمام",
          "Location services are disabled": "خدمات الموقع معطلة",
          "Location permissions are permanently denied, we cannot request permissions": "يتم رفض أذونات الموقع بشكل دائم ، لا يمكننا طلب أذونات",
          "We already have product with other freelancer": "لدينا بالفعل منتج مع مستقل آخر",
          "We already have service or package with other salon or with freelancer": "لدينا بالفعل خدمة أو حزمة مع صالون آخر أو مع Freelancer",
          "Sorry we deliver the order near to": "آسف نحن نقدم الطلب بالقرب من",
          "Appoinments once placed cannot be cancelled and non-refundable": "لا يمكن إلغاء التوعية بمجرد وضعها وغير قابلة للاسترداد",
          "Are you sure": "هل أنت واثق",
          "Thank You!": "شكرا لك!",
          "For Your Appoinment": "للتنسيق الخاص بك",
          "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout":
              "إنها حقيقة راسخة أن القارئ سوف يصرف انتباهه عن طريق المحتوى القابل للقراءة للصفحة عند النظر إلى تخطيطه",
          "TRACK MY APPOINTMENT": "تتبع موعدي",
          "BACK TO HOME": "العودة إلى المنزل",
          "Sunday": "الأحد",
          "Monday": "الاثنين",
          "Tuesday": "يوم الثلاثاء",
          "Wednesday": "الأربعاء",
          "Thursday": "يوم الخميس",
          "Friday": "جمعة",
          "Saturday": "السبت",
          "Please select Slots": "الرجاء تحديد فتحات",
          "Email is not valid": "البريد الإلكتروني غير صالح",
          "Access denied": "تم الرفض",
          "error": "خطأ",
          "Phone Number is required": "رقم الهاتف مطلوب",
          "Something went wrong while signup": "حدث خطأ ما أثناء الاشتراك",
          "Something went wrong": "هناك خطأ ما",
          "Verification": "تَحَقّق",
          "We have sent verification code on": "لقد أرسلنا رمز التحقق على",
          "Verify": "يؤكد",
          "Successfully Added": "أضيف بنجاح",
          "Successfully Updated": "تم التحديث بنجاح",
          "Please select payment method": "الرجاء تحديد طريقة الدفع",
          "We have already select product with other freelancer": "لقد اخترنا بالفعل منتجًا مع Freelancer الآخر",
          "Share with buddies": "مشاركة مع الأصدقاء",
          "Copied to clipboard": "نسخ إلى الحافظة",
          "Hey Buddy download": "يا صديقي تنزيل",
          "Your friend": "صديقك",
          "has invited you to": "لقد دعتك إلى",
          "from app store and use my code": "من متجر التطبيقات واستخدم الكود الخاص بي",
          "while sign up we both will get": "بينما التسجيل سنحصل على كلانا",
          "wallet amount": "كمية المحفظة",
          "Password mismatch": "عدم تطابق كلمة المرور",
          "No Website Found": "لم يتم العثور على موقع ويب",
          "Please checkout this salon": "يرجى الخروج من هذا الصالون",
          "Share with": "شارك مع",
          "Please select specialist": "الرجاء تحديد أخصائي",
          "Yes, Place Order": "نعم ، ترتيب المكان",
          "Please select card": "الرجاء تحديد بطاقة",
          "Creating Order": "إنشاء ترتيب",
          "TRACK MY ORDERS": "تتبع طلباتي",
          "For Your Orders": "لأوامرك",
          "Order notes..": "ترتيب ملاحظات.."
        },
      };
}
